#!/usr/bin/env python3
"""Generate a fixed seated derivative; preserve the uploaded human URDF.

Run from any directory with NumPy/SciPy installed. These are generation-only
requirements; viewing the generated rider requires neither library.
"""
from pathlib import Path
import copy
import xml.etree.ElementTree as ET
import numpy as np
from scipy.spatial.transform import Rotation
from scipy.optimize import least_squares

PACKAGE = Path(__file__).resolve().parents[1]
SOURCE = PACKAGE.parent / 'humanSubject01/humanSubject01_66dof_colored.urdf'
OUTPUT = PACKAGE / 'model/seated_rider.urdf.xacro'


def generate():
    robot = ET.parse(SOURCE).getroot()
    joints = robot.findall('joint')
    angles = {j.get('name'): 0.0 for j in joints}
    angles['jL5S1_roty'] = 0.45
    angles['jT1C7_roty'] = -0.20
    for side in ('Left', 'Right'):
        angles[f'j{side}Hip_roty'] = -0.85
        angles[f'j{side}Knee_roty'] = 1.45
        angles[f'j{side}Ankle_roty'] = -0.60

    def transforms():
        frames = {'Pelvis': np.eye(4)}
        pending = list(joints)
        while pending:
            progressed = False
            for joint in pending[:]:
                parent = joint.find('parent').get('link')
                if parent not in frames:
                    continue
                origin = joint.find('origin')
                t = np.eye(4)
                t[:3, 3] = np.fromstring(origin.get('xyz', '0 0 0'), sep=' ')
                t[:3, :3] = Rotation.from_euler('xyz', np.fromstring(origin.get('rpy', '0 0 0'), sep=' ')).as_matrix()
                if joint.get('type') != 'fixed':
                    axis = np.fromstring(joint.find('axis').get('xyz'), sep=' ')
                    t[:3, :3] = t[:3, :3] @ Rotation.from_rotvec(axis * angles[joint.get('name')]).as_matrix()
                frames[joint.find('child').get('link')] = frames[parent] @ t
                pending.remove(joint)
                progressed = True
            if not progressed:
                raise ValueError('Disconnected or cyclic source human model')
        return frames

    # Targets relative to pelvis at (0.29, 0, 1.01) on the bicycle.
    # Fit both elbow and palm positions, retaining the source segment lengths.
    for side, sign in [('Left', 1), ('Right', -1)]:
        names = [f'j{side}{joint}_rot{axis}' for joint in ('Shoulder', 'Elbow') for axis in 'xyz']
        elbow_target = np.array([0.35, sign * 0.27, 0.24])
        palm_target = np.array([0.57, sign * 0.24, 0.09])
        def residual(values):
            angles.update(zip(names, values))
            frames = transforms()
            elbow = frames[side + 'ForeArm'][:3, 3]
            palm = (frames[side + 'Hand'] @ np.array([0, sign * 0.083588, 0, 1]))[:3]
            return np.r_[elbow-elbow_target, palm-palm_target, 0.002*values]
        result = least_squares(residual, np.zeros(6), bounds=(-2.8, 2.8), max_nfev=400)
        angles.update(zip(names, result.x))
        print(side, 'elbow/palm target error (m):', np.linalg.norm(residual(result.x)[:6]))

    output = ET.Element('robot', {'name': 'seated_rider'})
    output.append(ET.Comment(' Generated by scripts/generate_seated_rider.py from the uploaded colored 66-DoF URDF. Fixed preview pose; no pedaling/contact constraints. '))
    for link in robot.findall('link'):
        link = copy.deepcopy(link)
        link.set('name', 'rider_' + link.get('name'))
        # Source includes massless helper frames and zero-sized COM visuals.
        inertial = link.find('inertial')
        if inertial is not None and float(inertial.find('mass').get('value')) == 0:
            link.remove(inertial)
        for tag in ('visual', 'collision'):
            for element in link.findall(tag):
                box = element.find('geometry/box')
                if box is not None and min(map(float, box.get('size').split())) <= 0:
                    link.remove(element)
        for material in link.iter('material'):
            material.set('name', 'rider_' + material.get('name'))
        output.append(link)
    for joint in joints:
        joint = copy.deepcopy(joint)
        name = joint.get('name')
        if joint.get('type') != 'fixed':
            origin = joint.find('origin')
            rotation = Rotation.from_euler('xyz', np.fromstring(origin.get('rpy', '0 0 0'), sep=' '))
            axis = np.fromstring(joint.find('axis').get('xyz'), sep=' ')
            rpy = (rotation * Rotation.from_rotvec(axis * angles[name])).as_euler('xyz')
            origin.set('rpy', ' '.join(f'{v:.9f}' for v in rpy))
        joint.set('name', 'rider_' + name)
        joint.set('type', 'fixed')
        for tag in ('axis', 'limit', 'dynamics'):
            for element in joint.findall(tag):
                joint.remove(element)
        for tag in ('parent', 'child'):
            element = joint.find(tag)
            element.set('link', 'rider_' + element.get('link'))
        output.append(joint)
    ET.indent(output, space='  ')
    ET.ElementTree(output).write(OUTPUT, encoding='utf-8', xml_declaration=True)
    print('Generated', OUTPUT)


if __name__ == '__main__':
    generate()
